language: node_js
node_js:
- "node"
- "lts/*"
before_install:
  - npm install grunt-cli
  - docker-compose build
install:
  - grunt install
cache:
  directories:
  - "$HOME/.npm"

before_script:
  - docker-compose up -d

script:
  - grunt test
  - wget http://localhost:8080/grupos/ || exit 1