version: '3'

networks:
  lyricshunter:
      driver: bridge

volumes:
  .:    
   driver: local  

services:
   
   grupos_service00:
      container_name: grupos00
      build:
         context: .
         dockerfile: despliegue.Dockerfile    
      ports:
         - "3001:3000"
   
   grupos_service01:
      container_name: grupos01
      build:
         context: .
         dockerfile: despliegue.Dockerfile    
      ports:
         - "3002:3000"
      
      
   nginx:
      image: nginx:alpine
      container_name: nginx 
      restart: always
      ports:
         - 80:80
      volumes:
         - ./Config/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf    # dir para archivo configuración de nginx 
         - ./Config/nginx/logs:/var/log/nginx      
      depends_on:
         - grupos_service00
         - grupos_service01
        
   