version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test

jobs: 
  test: 
    docker: 
      - image: angelvalera/lyricshunter:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD    
    steps:
      - run: pwd
      - run: ls -l
      - run: ls /app
      - run: 
          name: Testing
          command: grunt test
