version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: angelvalera/lyricshunter
    steps:
      - checkout
      - run:
          name: Testing
          command: grunt test
