version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: angelvalera/lyricshunter:latest
        auth:
          username: $DOCKERHUB_USERNAME  
          password: $DOCKERHUB_PASSWORD  
    
      steps:
      - checkout
      - run: pwd
      - run:
          name: Testing
          command: grunt test
