// Códigos de pais según ISO 3166-1 alfa-2
const codPais = Object.freeze({ 
    'Andorra': 'AD', 
    'Austria': 'AT',
    'Australia': 'AU',
    'Bélgica': 'BE',
    'Bulgaria': 'BG',
    'Bolivia': 'BO',
    'Brasil': 'BR',    
    'Canadá': 'CA', 	
    'Congo': 'CG', 	 
    'Suiza': 'CH', 	
    'Chile': 'CL', 	
    'China': 'CN', 	
    'Colombia': 'CO',
    'Costa Rica': 'CR',
    'Cuba': 'CU',
    'Chipre': 'CY',
    'Republica Checa': 'CZ',
    'Alemania': 'DE',
    'Dinamarca': 'DK',
    'Ecuador': 'EC',
    'Egipto': 'EG',
    'España': 'ES',
    'Finlandia': 'FI',
    'Francia': 'FR',
    'Reino Unido': 'GB',
    'Georgia': 'GE',
    'Grecia': 'GR',
    'Guatemala': 'GT',
    'Honduras': 'HN',
    'Croacia': 'HR',
    'Hungría': 'HU',
    'Irlanda': 'IE',
    'Israel': 'IL',
    'India': 'IN',
    'Irak': 'IQ',
    'Irán': 'IR',
    'Islandia': 'IS',
    'Italia': 'IT',
    'Jamaica': 'JM',
    'Japón': 'JP',
    'Corea del Norte': 'KP',
    'Corea del Sur': 'KR',
    'Kuwait': 'KW',
    'Líbano': 'LB',
    'Lituania': 'LT',
    'Luxemburgo': 'LU',
    'Letonia': 'LV',
    'Libia': 'LY',
    'Marruecos': 'MA',
    'Macedonia': 'MK',
    'México': 'MX',
    'Países Bajos': 'NL',
    'Noruega': 'NO',
    'Nueva Zelanda': 'NZ',
    'Panamá': 'PA',
    'Perú': 'PE',
    'Polonia': 'PL',
    'Puerto Rico': 'PR',
    'Portugal': 'PT',
    'Rumanía': 'RO',
    'Rusia': 'RU',    
    'Suecia': 'SE',
    'Eslovenia': 'SI',
    'Eslovaquia': 'SK',
    'Túnez': 'TN',
    'Turquía': 'TR',
    'Ucrania': 'UA',
    'Uganda': 'UG',
    'Estados Unidos': 'US',
    'Uruguay': 'UY',
    'Venezuela': 'VE',
    'Vietnam': 'VN',
    'Sudáfrica': 'ZA' 
});

module.exports = codPais;