name: Comprobar que docker compose funciona
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Construye el cluster
        run: docker-compose up -d
      - name: Testea el cluster
        run: |
          wget http://localhost:80/grupos/ || exit 1
          wget http://localhost:80/canciones/ || exit 1
          wget http://localhost:80/usuarios/ || exit 1
