name: Comprobar que docker compose funciona
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Construye el cluster
        run: docker-compose up -d      
      - name: Testea el cluster separado
        run: |
          wget http://localhost:3001/grupos || exit 1
          wget http://localhost:3001/canciones || exit 1
          wget http://localhost:3001/usuarios || exit 1
          wget http://localhost:3002/grupos || exit 1
          wget http://localhost:3002/canciones || exit 1
          wget http://localhost:3002/usuarios || exit 1
      - name: Testea el cluster en conjunto
        run: |
          wget http://localhost:8080/grupos || exit 1
          wget http://localhost:8080/canciones || exit 1
          wget http://localhost:8080/usuarios || exit 1